# Generated by Django 3.1.7 on 2023-01-11 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('git_repo', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
