// Types

// Projects
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL';

//Contact
export const SEND_EMAIL_SUCCES = 'SEND_EMAIL_SUCCES';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';

// EDUCATION
export const GET_EDUCATION_SUCCESS = 'GET_EDUCATION_SUCCESS';
export const GET_EDUCATION_FAIL = 'GET_EDUCATION_FAIL';

// EXPERIENCE
export const GET_EXPERIENCE_SUCCESS = 'GET_EXPERIENCE_SUCCESS';
export const GET_EXPERIENCE_FAIL = 'GET_EXPERIENCE_FAIL';