# Generated by Django 3.1.7 on 2023-01-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('year_start', models.CharField(max_length=4)),
                ('year_end', models.CharField(blank=True, max_length=4)),
                ('company', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('detail_1', models.TextField()),
                ('detail_2', models.TextField(blank=True)),
                ('detail_3', models.TextField(blank=True)),
            ],
        ),
    ]
