# Generated by Django 3.1.7 on 2023-01-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Maxima'), (2, 'Alta'), (4, 'Baja'), (3, 'Media')]),
        ),
    ]
