# Generated by Django 3.1.7 on 2023-01-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20230114_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Maxima'), (2, 'Alta'), (3, 'Media'), (4, 'Baja')]),
        ),
    ]
