# Generated by Django 3.1.7 on 2023-01-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20230114_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='priority',
            field=models.IntegerField(choices=[(2, 'Alta'), (4, 'Baja'), (1, 'Maxima'), (3, 'Media')]),
        ),
    ]
