# Generated by Django 3.1.7 on 2023-01-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20230114_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='priority',
            field=models.IntegerField(choices=[(4, 'Baja'), (3, 'Media'), (2, 'Alta'), (1, 'Maxima')]),
        ),
    ]
